language: node_js
node_js:
  - node
cache: yarn
script: echo Tests disabled.
before_deploy: yarn version --no-git-tag-version --new-version "$TRAVIS_TAG"
deploy:
  provider: npm
  on:
    tags: true
  email: admin@rinq.io
  api_key:
    secure: zJBrHrbm2aZm1e+4jPXdtioBvEQXGJtK0xjOUUcsmrZD6oeafRbiwVZFZQUHXv83rQERPdalonElFVhHEhjBFb+600pvWta6jpWSbf8MMrV8+RVTm6Nt1IYqNV/0wE4smT6xdZGC0k10eo6W10+hKdQTnG2QRjMrTyMi7cvYK0FyzrX5FipQtvMsI4wpZtpn4WqSzHFdci/pfc1/oWiIkd+EF0kfGRV6CPYvqS+iuW7ZLxi2MLzt1S6ITDa+SKbEsmwriDsrpP9mskBCzkt9LVdStjvNhtmSUGEtnshpDe6cUya2xV2FqhvMQl0cBMQFQfeLly396tTGvUOtWdczkUlgVJdW8rK4kP8qvuv8B9FVJuo5mFW6+ke3mF5XUAp5tU2mk/m7JY86jeCTkI1G7Bxfh+bGKq4dcDsebWj5MoCGj75+34inmlg3/mBHVoaMmY1R+9knRvCJGYLDKozQWLdzyeDa1zEo76JVtMcr7oFbY35zAAgPgJD+DVMOrBJjEwMYbLZ123iEWbvnrEdW1RYzqiYYo+9BCIujcNX18FqJvmLVlfQszm0f05jXWWpYsEydSyn4OCao3z780Ddk0t4X7MyBYRnoRq3D3whnVa5INd+xer0Sq0HBuWUeHI4LVRcQHaCZmQeNKgcDpftTURb1QvtWakfJutqpuOtYHa4=
